# version: 2
# updates:
# - package-ecosystem: npm
#   directory: "/ProjectExam"
#   schedule:
#     interval: monthly
#     time: "04:00"
#   open-pull-requests-limit: 10
# - package-ecosystem: npm
#   directory: "/InfoTech"
#   schedule:
#     interval: monthly
#     time: "04:00"
#   open-pull-requests-limit: 10
